version: '3.4'

volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,noacl,nocto,noatime,nodiratime,soft,nolock,rsize=32768,wsize=32768,intr,tcp,nfsvers=3,actimeo=2
            device: ":${PWD}"

services:

    apache:
        build: apache2/
        container_name: docker_nfs_apache2
        ports:
            - 80:80
        volumes:
            - ./apache2/vhosts:/etc/apache2/sites-enabled:delegated
            - 'nfsmount:/var/www/html'

        depends_on:
            - php

    php:
        build: php/
        container_name: docker_nfs_php
        volumes:
          - 'nfsmount:/var/www/html'
